version: "3"
# docker-compose -f docker-compose.db.yml up
# docker-compose -f docker-compose.db.yml up -d
services:

###########################
#       dev-database      #
###########################
  dev-database: 
    container_name: dev-postgres-database
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes: 
      - ./pgdata:/var/lib/postgresql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql